### ISSUE TITLE
Caracteres especiais com codificação ' j\u00e1'

### ISSUE THREAD

**Issue by LuquinhasMoraes** [enniosousa/laravel-5.5-pt-BR-localization#3]
Olá, primeiramente valeu pela disponibilização do pacote! 

Estou meio enferrujado com PHP e gostaria de saber pq todas minhas msgs estão vindo assim, por exemplo: 

"O campo name j\u00e1 est\u00e1 sendo utilizado"

Sei que o problema provavelmente está no meu código, mas será q alguém pode me ajudar?

**Comment by enniosousa** [comment]
Essa codificação aparece quando a mensagem de erro aparece em HTML ou você
está retornando ao a mensagem de erro em JSON?

Se for em JSON é desse jeito mesmo. Quando você exibir a mensagem pelo
Javascript a acentuação aparecerá corretamente.

Em ter, 10 de abr de 2018 22:54, LuquinhasMoraes <notifications@github.com>
escreveu:
